<?php
/**
 * Tracker class for Loremix Demo Content Generator.
 *
 * Stores and retrieves the IDs of all content generated by this plugin
 * inside wp_options rows. Acts as a redundant safety layer alongside
 * the `_wpdcg_generated` post meta flag.
 *
 * All methods are static — no instantiation required.
 *
 * @package Loremix_Demo_Content_Generator
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WPDCG_Tracker
 */
class WPDCG_Tracker {

	/** wp_options key for generated post IDs. */
	const OPTION_KEY = 'wpdcg_generated_ids';

	/** wp_options key for batch metadata. */
	const BATCH_OPTION_KEY = 'wpdcg_batches';

	/** wp_options key for generated comment IDs. */
	const COMMENT_OPTION_KEY = 'wpdcg_comment_ids';

	/** wp_options key for generated user IDs. */
	const USER_OPTION_KEY = 'wpdcg_user_ids';

	/** wp_options key for generated WC order IDs. */
	const ORDER_OPTION_KEY = 'wpdcg_order_ids';

	// ── Flat ID list ─────────────────────────────────────────────────────────

	/**
	 * Returns all tracked post IDs.
	 *
	 * @return int[]
	 */
	public static function get_all_ids() {
		$ids = get_option( self::OPTION_KEY, array() );
		return is_array( $ids ) ? array_values( array_map( 'absint', $ids ) ) : array();
	}

	/**
	 * Merges new IDs into the tracked list.
	 *
	 * @param int[] $ids Post IDs to add.
	 */
	public static function add_ids( array $ids ) {
		$existing = self::get_all_ids();
		$merged   = array_values( array_unique( array_merge( $existing, array_map( 'absint', $ids ) ) ) );
		update_option( self::OPTION_KEY, $merged, false );
	}

	/**
	 * Removes specific IDs from the tracked list.
	 *
	 * @param int[] $ids Post IDs to remove.
	 */
	public static function remove_ids( array $ids ) {
		$existing = self::get_all_ids();
		$remove   = array_map( 'absint', $ids );
		$updated  = array_values( array_diff( $existing, $remove ) );
		update_option( self::OPTION_KEY, $updated, false );
	}

	/**
	 * Wipes all tracked IDs and batch records from the database.
	 */
	public static function clear() {
		delete_option( self::OPTION_KEY );
		delete_option( self::BATCH_OPTION_KEY );
		delete_option( self::COMMENT_OPTION_KEY );
		delete_option( self::USER_OPTION_KEY );
		delete_option( self::ORDER_OPTION_KEY );
	}

	/**
	 * Returns the total number of tracked post items.
	 *
	 * @return int
	 */
	public static function count() {
		return count( self::get_all_ids() );
	}

	// ── Comment IDs ──────────────────────────────────────────────────────────

	public static function get_comment_ids(): array {
		$ids = get_option( self::COMMENT_OPTION_KEY, array() );
		return is_array( $ids ) ? array_values( array_map( 'absint', $ids ) ) : array();
	}

	public static function add_comment_ids( array $ids ): void {
		$merged = array_values( array_unique( array_merge( self::get_comment_ids(), array_map( 'absint', $ids ) ) ) );
		update_option( self::COMMENT_OPTION_KEY, $merged, false );
	}

	public static function remove_comment_ids( array $ids ): void {
		$updated = array_values( array_diff( self::get_comment_ids(), array_map( 'absint', $ids ) ) );
		update_option( self::COMMENT_OPTION_KEY, $updated, false );
	}

	public static function count_comments(): int {
		return count( self::get_comment_ids() );
	}

	// ── User IDs ─────────────────────────────────────────────────────────────

	public static function get_user_ids(): array {
		$ids = get_option( self::USER_OPTION_KEY, array() );
		return is_array( $ids ) ? array_values( array_map( 'absint', $ids ) ) : array();
	}

	public static function add_user_ids( array $ids ): void {
		$merged = array_values( array_unique( array_merge( self::get_user_ids(), array_map( 'absint', $ids ) ) ) );
		update_option( self::USER_OPTION_KEY, $merged, false );
	}

	public static function remove_user_ids( array $ids ): void {
		$updated = array_values( array_diff( self::get_user_ids(), array_map( 'absint', $ids ) ) );
		update_option( self::USER_OPTION_KEY, $updated, false );
	}

	public static function count_users(): int {
		return count( self::get_user_ids() );
	}

	// ── Order IDs ─────────────────────────────────────────────────────────────

	public static function get_order_ids(): array {
		$ids = get_option( self::ORDER_OPTION_KEY, array() );
		return is_array( $ids ) ? array_values( array_map( 'absint', $ids ) ) : array();
	}

	public static function add_order_ids( array $ids ): void {
		$merged = array_values( array_unique( array_merge( self::get_order_ids(), array_map( 'absint', $ids ) ) ) );
		update_option( self::ORDER_OPTION_KEY, $merged, false );
	}

	public static function remove_order_ids( array $ids ): void {
		$updated = array_values( array_diff( self::get_order_ids(), array_map( 'absint', $ids ) ) );
		update_option( self::ORDER_OPTION_KEY, $updated, false );
	}

	public static function count_orders(): int {
		return count( self::get_order_ids() );
	}

	// ── Batch metadata ───────────────────────────────────────────────────────

	/**
	 * Records a new batch with its metadata.
	 *
	 * @param string $batch_id  Batch identifier.
	 * @param string $post_type Post type generated in this batch.
	 * @param int[]  $ids       Post IDs created in this batch.
	 */
	public static function add_batch( string $batch_id, string $post_type, array $ids ) {
		$batches   = get_option( self::BATCH_OPTION_KEY, array() );
		$batches   = is_array( $batches ) ? $batches : array();
		$batches[] = array(
			'id'        => $batch_id,
			'post_type' => $post_type,
			'count'     => count( $ids ),
			'created'   => time(),
			'ids'       => array_map( 'absint', $ids ),
		);
		update_option( self::BATCH_OPTION_KEY, $batches, false );
	}

	/**
	 * Returns all recorded batches, newest first.
	 *
	 * @return array[]
	 */
	public static function get_batches(): array {
		$batches = get_option( self::BATCH_OPTION_KEY, array() );
		if ( ! is_array( $batches ) ) {
			return array();
		}
		return array_reverse( $batches );
	}

	/**
	 * Returns the post IDs belonging to a specific batch.
	 *
	 * @param string $batch_id
	 * @return int[]
	 */
	public static function get_batch_ids( string $batch_id ): array {
		foreach ( self::get_batches() as $batch ) {
			if ( isset( $batch['id'] ) && $batch['id'] === $batch_id ) {
				return isset( $batch['ids'] ) ? array_map( 'absint', (array) $batch['ids'] ) : array();
			}
		}
		return array();
	}

	/**
	 * Removes a specific batch from the tracking list.
	 *
	 * @param string $batch_id
	 */
	public static function remove_batch( string $batch_id ) {
		$batches = get_option( self::BATCH_OPTION_KEY, array() );
		if ( ! is_array( $batches ) ) {
			return;
		}
		$batches = array_values(
			array_filter(
				$batches,
				function ( $b ) use ( $batch_id ) {
					return isset( $b['id'] ) && $b['id'] !== $batch_id;
				}
			)
		);
		update_option( self::BATCH_OPTION_KEY, $batches, false );
	}
}
