<?php
/**
 * Cleaner class for QuickDemo Content Generator.
 *
 * Safely deletes ONLY the content generated by this plugin.
 * Routes deletion by batch type prefix (_comment, _user, _wc_review, _wc_order)
 * so each content type is cleaned up correctly.
 *
 * @package QuickDemo_Content_Generator
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WPDCG_Cleaner
 */
class WPDCG_Cleaner {

	/**
	 * Deletes ALL demo content generated by this plugin across all types.
	 *
	 * @return array { deleted: int, errors: string[] }
	 */
	public function delete_all(): array {
		$deleted = 0;
		$errors  = array();

		$this->backfill_source_meta_from_tracker();

		// Posts (any type).
		$result   = $this->delete_demo_posts();
		$deleted += $result['deleted'];
		$errors   = array_merge( $errors, $result['errors'] );

		// Comments and WC reviews (identified by comment meta).
		$this->backfill_comment_source_meta_from_tracker();
		$result   = $this->delete_demo_comments();
		$deleted += $result['deleted'];
		$errors   = array_merge( $errors, $result['errors'] );

		// Users.
		$this->backfill_user_source_meta_from_tracker();
		$result   = $this->delete_demo_users();
		$deleted += $result['deleted'];
		$errors   = array_merge( $errors, $result['errors'] );

		// WC orders.
		$this->backfill_order_source_meta_from_tracker();
		$result   = $this->delete_demo_orders();
		$deleted += $result['deleted'];
		$errors   = array_merge( $errors, $result['errors'] );

		// Demo navigation menus.
		if ( class_exists( 'WPDCG_Menu_Generator' ) ) {
			$deleted += WPDCG_Menu_Generator::delete_all_menus();
		}

		// Auto-generated taxonomy terms.
		$this->delete_auto_terms();

		WPDCG_Tracker::clear();

		return array(
			'deleted' => $deleted,
			'errors'  => $errors,
		);
	}

	/**
	 * Deletes all demo content belonging to a specific batch.
	 * Routes by the batch type prefix stored in the tracker.
	 *
	 * @param string $batch_id Batch identifier.
	 * @return array { deleted: int, errors: string[] }
	 */
	public function delete_batch( string $batch_id ): array {
		if ( ! $batch_id ) {
			return array( 'deleted' => 0, 'errors' => array() );
		}

		$type = $this->get_batch_type( $batch_id );

		if ( '_comment' === $type || '_wc_review' === $type ) {
			$this->backfill_comment_source_meta_for_batch( $batch_id );
			return $this->delete_batch_comments( $batch_id );
		}
		if ( '_user' === $type ) {
			$this->backfill_user_source_meta_for_batch( $batch_id );
			return $this->delete_batch_users( $batch_id );
		}
		if ( '_wc_order' === $type ) {
			$this->backfill_order_source_meta_for_batch( $batch_id );
			return $this->delete_batch_orders( $batch_id );
		}
		if ( '_menu' === $type && class_exists( 'WPDCG_Menu_Generator' ) ) {
			$deleted = WPDCG_Menu_Generator::delete_menu_batch( $batch_id );
			return array( 'deleted' => $deleted, 'errors' => array() );
		}

		// Default: posts and media attachments (both are WP posts).
		$this->backfill_post_source_meta_for_batch( $batch_id );
		return $this->delete_batch_posts( $batch_id );
	}

	// ── Type-specific deleters ────────────────────────────────────────────────

	private function delete_demo_posts(): array {
		$query = new WP_Query(
			array(
				'post_type'      => $this->get_deletable_post_types(),
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
					'relation' => 'AND',
					array(
						'key'   => WPDCG_Generator::META_KEY,
						'value' => '1',
					),
					array(
						'key'   => WPDCG_Generator::SOURCE_META_KEY,
						'value' => WPDCG_Generator::SOURCE_VALUE,
					),
				),
			)
		);

		$deleted = 0;
		$errors  = array();

		foreach ( $query->posts as $post_id ) {
			if ( wp_delete_post( absint( $post_id ), true ) instanceof WP_Post ) {
				$deleted++;
			} else {
				$errors[] = sprintf( __( 'Could not delete post ID %d.', 'quickdemo-content-generator' ), absint( $post_id ) ); // phpcs:ignore WordPress.WP.I18n.MissingTranslatorsComment
			}
		}

		return array( 'deleted' => $deleted, 'errors' => $errors );
	}

	private function delete_demo_comments(): array {
		global $wpdb;

		$comment_ids = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT generated.comment_id
				FROM {$wpdb->commentmeta} generated
				INNER JOIN {$wpdb->commentmeta} source
					ON source.comment_id = generated.comment_id
				WHERE generated.meta_key = %s
					AND generated.meta_value = %s
					AND source.meta_key = %s
					AND source.meta_value = %s",
				WPDCG_Comment_Generator::COMMENT_META_KEY,
				'1',
				WPDCG_Generator::SOURCE_META_KEY,
				WPDCG_Generator::SOURCE_VALUE
			)
		);

		$deleted = 0;
		$errors  = array();

		foreach ( $comment_ids as $comment_id ) {
			if ( wp_delete_comment( absint( $comment_id ), true ) ) {
				$deleted++;
			}
		}

		return array( 'deleted' => $deleted, 'errors' => $errors );
	}

	private function delete_demo_users(): array {
		require_once ABSPATH . 'wp-admin/includes/user.php';

		$user_ids = WPDCG_Tracker::get_user_ids();
		$deleted  = 0;
		$errors   = array();

		foreach ( $user_ids as $user_id ) {
			if (
				'1' !== (string) get_user_meta( $user_id, WPDCG_User_Generator::USER_META_KEY, true )
				|| WPDCG_Generator::SOURCE_VALUE !== (string) get_user_meta( $user_id, WPDCG_Generator::SOURCE_META_KEY, true )
			) {
				continue;
			}

			if ( wp_delete_user( absint( $user_id ) ) ) {
				$deleted++;
			} else {
				$errors[] = sprintf( __( 'Could not delete user ID %d.', 'quickdemo-content-generator' ), absint( $user_id ) ); // phpcs:ignore WordPress.WP.I18n.MissingTranslatorsComment
			}
		}

		return array( 'deleted' => $deleted, 'errors' => $errors );
	}

	private function delete_demo_orders(): array {
		if ( ! function_exists( 'wc_get_order' ) ) {
			return array( 'deleted' => 0, 'errors' => array() );
		}

		$order_ids = WPDCG_Tracker::get_order_ids();
		$deleted   = 0;
		$errors    = array();

		foreach ( $order_ids as $order_id ) {
			$order = wc_get_order( absint( $order_id ) );
			if ( $order ) {
				if (
					'1' !== (string) $order->get_meta( WPDCG_Woo_Generator::ORDER_META_KEY )
					|| WPDCG_Generator::SOURCE_VALUE !== (string) $order->get_meta( WPDCG_Generator::SOURCE_META_KEY )
				) {
					continue;
				}

				$order->delete( true );
				$deleted++;
			}
		}

		return array( 'deleted' => $deleted, 'errors' => $errors );
	}

	private function delete_auto_terms(): void {
		$public_taxes = get_taxonomies( array( 'public' => true ) );
		if ( empty( $public_taxes ) ) {
			return;
		}

		$auto_terms = get_terms( array(
			'taxonomy'               => array_values( $public_taxes ),
			'hide_empty'             => false,
			'number'                 => 0,
			'update_term_meta_cache' => false,
			'meta_query'             => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
				array(
					'key'   => WPDCG_Generator::TERM_META_KEY,
					'value' => '1',
				),
			),
		) );

		if ( ! is_wp_error( $auto_terms ) ) {
			foreach ( $auto_terms as $term ) {
				wp_delete_term( $term->term_id, $term->taxonomy );
			}
		}
	}

	// ── Batch-scoped deleters ─────────────────────────────────────────────────

	private function delete_batch_posts( string $batch_id ): array {
		$query = new WP_Query(
			array(
				'post_type'      => $this->get_deletable_post_types(),
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
					'relation' => 'AND',
					array(
						'key'   => WPDCG_Generator::META_KEY,
						'value' => '1',
					),
					array(
						'key'   => WPDCG_Generator::BATCH_META_KEY,
						'value' => $batch_id,
					),
					array(
						'key'   => WPDCG_Generator::SOURCE_META_KEY,
						'value' => WPDCG_Generator::SOURCE_VALUE,
					),
				),
			)
		);

		$deleted     = 0;
		$errors      = array();
		$deleted_ids = array();

		foreach ( $query->posts as $post_id ) {
			if ( wp_delete_post( absint( $post_id ), true ) instanceof WP_Post ) {
				$deleted++;
				$deleted_ids[] = absint( $post_id );
			} else {
				$errors[] = sprintf( __( 'Could not delete post ID %d.', 'quickdemo-content-generator' ), absint( $post_id ) ); // phpcs:ignore WordPress.WP.I18n.MissingTranslatorsComment
			}
		}

		if ( ! empty( $deleted_ids ) ) {
			WPDCG_Tracker::remove_ids( $deleted_ids );
		}
		WPDCG_Tracker::remove_batch( $batch_id );

		return array( 'deleted' => $deleted, 'errors' => $errors );
	}

	/**
	 * Returns all post types that may carry QuickDemo tracking meta.
	 *
	 * WP_Query's post_type=any excludes some internal/non-searchable types,
	 * including WooCommerce product_variation. Generated variations are stamped
	 * with batch meta and must be included for per-batch cleanup.
	 *
	 * @return string[]
	 */
	private function get_deletable_post_types(): array {
		return array_values( get_post_types( array(), 'names' ) );
	}

	/**
	 * Adds the newer QuickDemo source marker to IDs already recorded in the
	 * tracker, so older generated batches remain cleanable without widening
	 * delete-all to arbitrary posts with the legacy meta key.
	 */
	private function backfill_source_meta_from_tracker(): void {
		foreach ( WPDCG_Tracker::get_all_ids() as $post_id ) {
			if ( ! get_post( $post_id ) ) {
				continue;
			}

			if ( '1' === (string) get_post_meta( $post_id, WPDCG_Generator::META_KEY, true ) ) {
				update_post_meta( $post_id, WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}

		foreach ( WPDCG_Tracker::get_batches() as $batch ) {
			$batch_id = isset( $batch['id'] ) ? sanitize_key( (string) $batch['id'] ) : '';
			if ( '' === $batch_id ) {
				continue;
			}

			$query = new WP_Query(
				array(
					'post_type'      => $this->get_deletable_post_types(),
					'post_status'    => 'any',
					'posts_per_page' => -1,
					'fields'         => 'ids',
					'no_found_rows'  => true,
					'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
						'relation' => 'AND',
						array(
							'key'   => WPDCG_Generator::META_KEY,
							'value' => '1',
						),
						array(
							'key'   => WPDCG_Generator::BATCH_META_KEY,
							'value' => $batch_id,
						),
					),
				)
			);

			foreach ( $query->posts as $post_id ) {
				update_post_meta( absint( $post_id ), WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}
	}

	/**
	 * Backfills source markers onto post-like items in a specific batch.
	 *
	 * @param string $batch_id Batch identifier.
	 */
	private function backfill_post_source_meta_for_batch( string $batch_id ): void {
		$query = new WP_Query(
			array(
				'post_type'      => $this->get_deletable_post_types(),
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
					'relation' => 'AND',
					array(
						'key'   => WPDCG_Generator::META_KEY,
						'value' => '1',
					),
					array(
						'key'   => WPDCG_Generator::BATCH_META_KEY,
						'value' => $batch_id,
					),
				),
			)
		);

		foreach ( $query->posts as $post_id ) {
			update_post_meta( absint( $post_id ), WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
		}
	}

	/**
	 * Backfills source markers onto tracked comments/reviews from older batches.
	 */
	private function backfill_comment_source_meta_from_tracker(): void {
		foreach ( WPDCG_Tracker::get_comment_ids() as $comment_id ) {
			if ( get_comment( $comment_id ) && '1' === (string) get_comment_meta( $comment_id, WPDCG_Comment_Generator::COMMENT_META_KEY, true ) ) {
				update_comment_meta( $comment_id, WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}
	}

	/**
	 * Backfills source markers onto comments/reviews in a specific batch.
	 *
	 * @param string $batch_id Batch identifier.
	 */
	private function backfill_comment_source_meta_for_batch( string $batch_id ): void {
		foreach ( WPDCG_Tracker::get_batch_ids( $batch_id ) as $comment_id ) {
			if ( get_comment( $comment_id ) && '1' === (string) get_comment_meta( $comment_id, WPDCG_Comment_Generator::COMMENT_META_KEY, true ) ) {
				update_comment_meta( $comment_id, WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}
	}

	/**
	 * Backfills source markers onto tracked users from older batches.
	 */
	private function backfill_user_source_meta_from_tracker(): void {
		foreach ( WPDCG_Tracker::get_user_ids() as $user_id ) {
			if ( get_user_by( 'id', $user_id ) && '1' === (string) get_user_meta( $user_id, WPDCG_User_Generator::USER_META_KEY, true ) ) {
				update_user_meta( $user_id, WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}
	}

	/**
	 * Backfills source markers onto users in a specific batch.
	 *
	 * @param string $batch_id Batch identifier.
	 */
	private function backfill_user_source_meta_for_batch( string $batch_id ): void {
		foreach ( WPDCG_Tracker::get_batch_ids( $batch_id ) as $user_id ) {
			if ( get_user_by( 'id', $user_id ) && '1' === (string) get_user_meta( $user_id, WPDCG_User_Generator::USER_META_KEY, true ) ) {
				update_user_meta( $user_id, WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			}
		}
	}

	/**
	 * Backfills source markers onto tracked WooCommerce orders from older batches.
	 */
	private function backfill_order_source_meta_from_tracker(): void {
		foreach ( WPDCG_Tracker::get_order_ids() as $order_id ) {
			$this->backfill_single_order_source_meta( $order_id );
		}
	}

	/**
	 * Backfills source markers onto WooCommerce orders in a specific batch.
	 *
	 * @param string $batch_id Batch identifier.
	 */
	private function backfill_order_source_meta_for_batch( string $batch_id ): void {
		foreach ( WPDCG_Tracker::get_batch_ids( $batch_id ) as $order_id ) {
			$this->backfill_single_order_source_meta( $order_id );
		}
	}

	/**
	 * Adds source meta to one order if it already has QuickDemo order meta.
	 *
	 * @param int $order_id Order ID.
	 */
	private function backfill_single_order_source_meta( int $order_id ): void {
		if ( ! function_exists( 'wc_get_order' ) ) {
			return;
		}

		$order = wc_get_order( absint( $order_id ) );
		if ( $order && '1' === (string) $order->get_meta( WPDCG_Woo_Generator::ORDER_META_KEY ) ) {
			$order->update_meta_data( WPDCG_Generator::SOURCE_META_KEY, WPDCG_Generator::SOURCE_VALUE );
			$order->save();
		}
	}

	private function delete_batch_comments( string $batch_id ): array {
		global $wpdb;

		$comment_ids = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT batch.comment_id
				FROM {$wpdb->commentmeta} batch
				INNER JOIN {$wpdb->commentmeta} generated
					ON generated.comment_id = batch.comment_id
				INNER JOIN {$wpdb->commentmeta} source
					ON source.comment_id = batch.comment_id
				WHERE batch.meta_key = %s
					AND batch.meta_value = %s
					AND generated.meta_key = %s
					AND generated.meta_value = %s
					AND source.meta_key = %s
					AND source.meta_value = %s",
				WPDCG_Comment_Generator::BATCH_META_KEY,
				$batch_id,
				WPDCG_Comment_Generator::COMMENT_META_KEY,
				'1',
				WPDCG_Generator::SOURCE_META_KEY,
				WPDCG_Generator::SOURCE_VALUE
			)
		);

		$deleted     = 0;
		$deleted_ids = array();

		foreach ( $comment_ids as $comment_id ) {
			if ( wp_delete_comment( absint( $comment_id ), true ) ) {
				$deleted++;
				$deleted_ids[] = absint( $comment_id );
			}
		}

		if ( ! empty( $deleted_ids ) ) {
			WPDCG_Tracker::remove_comment_ids( $deleted_ids );
		}
		WPDCG_Tracker::remove_batch( $batch_id );

		return array( 'deleted' => $deleted, 'errors' => array() );
	}

	private function delete_batch_users( string $batch_id ): array {
		require_once ABSPATH . 'wp-admin/includes/user.php';
		global $wpdb;

		$user_ids = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$wpdb->prepare(
				"SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key = %s AND meta_value = %s",
				WPDCG_User_Generator::BATCH_META_KEY,
				$batch_id
			)
		);

		$deleted     = 0;
		$deleted_ids = array();

		foreach ( $user_ids as $user_id ) {
			if (
				'1' !== (string) get_user_meta( $user_id, WPDCG_User_Generator::USER_META_KEY, true )
				|| WPDCG_Generator::SOURCE_VALUE !== (string) get_user_meta( $user_id, WPDCG_Generator::SOURCE_META_KEY, true )
			) {
				continue;
			}

			if ( wp_delete_user( absint( $user_id ) ) ) {
				$deleted++;
				$deleted_ids[] = absint( $user_id );
			}
		}

		if ( ! empty( $deleted_ids ) ) {
			WPDCG_Tracker::remove_user_ids( $deleted_ids );
		}
		WPDCG_Tracker::remove_batch( $batch_id );

		return array( 'deleted' => $deleted, 'errors' => array() );
	}

	private function delete_batch_orders( string $batch_id ): array {
		if ( ! function_exists( 'wc_get_order' ) ) {
			return array( 'deleted' => 0, 'errors' => array() );
		}

		$order_ids = WPDCG_Tracker::get_batch_ids( $batch_id );
		$deleted   = 0;

		foreach ( $order_ids as $order_id ) {
			$order = wc_get_order( absint( $order_id ) );
			if ( $order ) {
				if (
					'1' !== (string) $order->get_meta( WPDCG_Woo_Generator::ORDER_META_KEY )
					|| WPDCG_Generator::SOURCE_VALUE !== (string) $order->get_meta( WPDCG_Generator::SOURCE_META_KEY )
				) {
					continue;
				}

				$order->delete( true );
				$deleted++;
			}
		}

		WPDCG_Tracker::remove_order_ids( $order_ids );
		WPDCG_Tracker::remove_batch( $batch_id );

		return array( 'deleted' => $deleted, 'errors' => array() );
	}

	// ── Helpers ───────────────────────────────────────────────────────────────

	private function get_batch_type( string $batch_id ): string {
		foreach ( WPDCG_Tracker::get_batches() as $batch ) {
			if ( isset( $batch['id'] ) && $batch['id'] === $batch_id ) {
				return isset( $batch['post_type'] ) ? (string) $batch['post_type'] : '';
			}
		}
		return '';
	}
}
